parameters:
- name: environmentTagName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: sharedEnvironmentId
  type: string
- name: serviceConnection
  type: string

stages:
- stage: Deploy_${{parameters.environmentId}}
  dependsOn:
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - group: platform-global
    - group: platform-global-findproviderapi
    - group: platform-${{parameters.environmentName}}
    - group: platform-${{parameters.environmentName}}-findproviderapi
    - name: BaseName
      value: "s126${{parameters.environmentId}}-fprapi-${{parameters.environmentName}}"
    - name: ResourceGroupName
      value: '$(BaseName)'
    - name: EnvironmentName
      value: ${{ parameters.environmentName }}
    - name: environmentTagName
      value: ${{parameters.environmentTagName}}

  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}] deployment'
  jobs:
  - template: ../jobs/findproviderapi-infrastructure-job.yml
    parameters:
      BaseName: $(BaseName)
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      environmentName: ${{parameters.environmentName}}

  - template: ../jobs/findproviderapi-publish-dacpac-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}

  - template: ../jobs/findproviderapi-generate-configs-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}

  # This is actually the job for the API despite the appName being ui
  - template: ../jobs/findproviderapi-publish-site-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      appName: 'ui'
      name: 'Website'
      dependencies:
        - DeployInfrastructure
        - GenerateConfigs
      package: 'Sfa.Tl.Find.Provider.Api.zip'

  # This is actually the job for the UI despite the appName being api
  - template: ../jobs/findproviderapi-publish-site-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      appName: 'api'
      name: 'FindProviderUI'
      dependencies:
        - DeployInfrastructure
        - GenerateConfigs
      package: 'Sfa.Tl.Find.Provider.Web.zip'

  # - template: ../jobs/findproviderapi-publish-function-job.yml
  #   parameters:
  #     serviceConnection: ${{ parameters.serviceConnection }}
  #     sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
