parameters:
- name: environmentTagName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: sharedEnvironmentId
  type: string
- name: serviceConnection
  type: string
- name: variableTemplates
  type: object
- name: applicationName
  type: string

stages:
- stage: Deploy_${{parameters.environmentId}}
  dependsOn:
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - group: platform-global
    - group: platform-global-findproviderapi
    - group: platform-${{parameters.environmentName}}
    - group: platform-${{parameters.environmentName}}-findproviderapi
    - group: platform-${{parameters.environmentName}}-findproviderapi-kv
    - name: BaseName
      value: "s126${{parameters.environmentId}}-fprapi-${{parameters.environmentName}}"
    - name: ResourceGroupName
      value: '$(BaseName)'
    - name: EnvironmentName
      value: ${{ parameters.environmentName }}
    - name: environmentTagName
      value: ${{parameters.environmentTagName}}
    - '${{ each variableTemplate in parameters.variableTemplates }}':
      - template: '${{variableTemplate}}'
    - name: SharedBaseName
      value: "s126${{parameters.sharedEnvironmentId}}-${{parameters.applicationName}}"
    - name: SharedResourceGroup
      value: '$(SharedBaseName)-shared' 


  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}] deployment'
  jobs:
  - template: ../jobs/findproviderapi-infrastructure-job.yml
    parameters:
      BaseName: $(BaseName)
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      environmentName: ${{parameters.environmentName}}

  - template: ../jobs/findproviderapi-publish-dacpac-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}

  - template: ../jobs/findproviderapi-generate-configs-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      environmentName: ${{parameters.environmentName}}
      ConfigurationSecrets:
        ApiSettingsApiKey: $(ApiSettingsApiKey)
        ApiSettingsAppId: $(ApiSettingsAppId)
        CourseDirectoryApiSettingsApiKey: $(CourseDirectoryApiSettingsApiKey)
        DfeSignInApiSecret: $(DfeSignInApiSecret)
        DfeSignInClientSecret: $(DfeSignInClientSecret)
        EmailSettingsGovNotifyApiKey: $(EmailSettingsGovNotifyApiKey)
        SQLServerAdminPassword: $(SQLServerAdminPassword)
        GoogleMapsApiSettingsApiKey: $(GoogleMapsApiSettingsApiKey)

  - template: ../jobs/findproviderapi-publish-site-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      appName: 'api'
      name: 'API'
      dependencies:
        - DeployInfrastructure
        - GenerateConfigs
      package: 'Sfa.Tl.Find.Provider.Api.zip'

  - template: ../jobs/findproviderapi-publish-site-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      appName: 'ui'
      name: 'UI'
      dependencies:
        - DeployInfrastructure
        - GenerateConfigs
      package: 'Sfa.Tl.Find.Provider.Web.zip'

  - template: ../jobs/findproviderapi-post-deployment-job.yml

  # - template: ../jobs/findproviderapi-publish-function-job.yml
  #   parameters:
  #     serviceConnection: ${{ parameters.serviceConnection }}
  #     sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
