resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
      ref: feature/TLD-376-remove-output-secrets
    - repository: devopsTools
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-tools

trigger:
  branches:
    include:
    - main
    - develop
    - feature/*
    - bugs/*
pr:
  - main
  - develop
  

variables:
- template: ./Automation/variables/vars-global.yml@devopsTemplates
- name: applicationName
  value: findpvdrapi
stages:
  - template: ./yaml/stages/findproviderapi-master-stage.yml
