parameters:
  - name: devEnvId
    displayName: The development environment id (defaults to 'd01')
    type: string
    default: d01
    values: 
      - d01
      - d02
      
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - main
    - develop
    - feature/*
    - bugs/*
pr:
  - main
  - develop
  

variables:
  applicationName: findpvdrapi
stages:
  - template: ./yaml/stages/findproviderapi-master-stage.yml
    parameters:
      devEnvId: ${{parameters.devEnvId}}
