parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
jobs:
- job: DeploySQLDatabase
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'
  dependsOn:
    - DeployfindproviderapiInfrastructure 

  variables:
    SharedResourceGroup: $[stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.SharedVariables.SharedResourceGroup']]
    SharedSQLServerName: $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.sharedSQLServerName'] ]
    DatabaseName: $[ dependencies.DeployfindproviderapiInfrastructure.outputs['armOutputs.armOutput.sqlDatabaseName'] ]
  steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'sqldrop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      displayName: Create temporary SQL firewall rule to allow Azure service connections
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az sql server firewall-rule create -g $(SharedResourceGroup) -s $(SharedSQLServerName) -n "allowAllAzure" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0'

    - task: SqlAzureDacpacDeployment@1
      displayName: 'Azure SQL Publish'
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        ServerName: '$(SharedSQLServerName).database.windows.net'
        DatabaseName: '$(DatabaseName)'
        SqlUsername: '$(SQLServerAdminUsername)'
        SqlPassword: '$(SQLServerAdminPassword)'
        DacpacFile: '$(System.ArtifactsDirectory)/sqldrop/src/Sfa.Tl.Find.Provider.Api.Database/bin/Release/Sfa.Tl.Find.Provider.Api.Database.dacpac'
        AdditionalArguments: '/p:GenerateSmartDefaults=True'

    - task: AzureCLI@2
      displayName: Remove temporary SQL firewall rule to allow Azure service connections
      inputs:
        azureSubscription: ${{parameters.serviceConnection}}
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az sql server firewall-rule delete -g $(SharedResourceGroup) -s $(SharedSQLServerName) -n "allowAllAzure"'

    - pwsh: | 
        $SqlConnectionString = "Server=tcp:$(SharedSQLServerName).database.windows.net,1433;Initial Catalog=$(DatabaseName);Persist Security Info=False;User ID=$(SQLServerAdminUsername);Password=$(SQLServerAdminPassword);MultipleActiveResultSets=True;Encrypt=true;TrustServerCertificate=False;Connection Timeout=1200;"
        Write-Host "##vso[task.setvariable variable=SqlConnectionString;isOutput=true]$SqlConnectionString"        
      name: SqlVariables

