parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
  - name: appName
    type: string
  - name: name
    type: string
  - name: dependencies
    type: object
  - name: package
    type: string
jobs:
- job: PublishSite_${{ parameters.name }}
  variables:
  - name: ConfigStorageAccountName
    value: $[stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.ConfigStorageAccountName']]
  - name: appName
    ${{ if eq( parameters['appName'], 'ui' )}}:
      value: $[dependencies.DeployfindproviderapiInfrastructure.outputs['armOutputs.armOutput.uiAppName']]
    ${{ elseif eq( parameters['appName'], 'api' )}}:
      value: $[dependencies.DeployfindproviderapiInfrastructure.outputs['armOutputs.armOutput.apiAppName']]

  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  dependsOn:
    - DeployfindproviderapiInfrastructure
    - GenerateConfigs
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'appdrop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureRmWebAppDeployment@3
    displayName: 'Azure App Service Deploy: $(appName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      WebAppName: $(appName)
      DeployToSlotFlag: true
      ResourceGroupName: '$(ResourceGroupName)'
      SlotName: 'staging'
      Package: '$(System.ArtifactsDirectory)/appdrop/${{ parameters.package }}'
      UseWebDeploy: true
      RemoveAdditionalFilesFlag: true

  - task: AzureAppServiceManage@0
    displayName: 'Start staging Slot: $(appName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      Action: 'Start Azure App Service'
      WebAppName: $(appName)
      SpecifySlotOrASE: true
      ResourceGroupName: '$(ResourceGroupName)'
      Slot: 'staging'

  - task: AzureAppServiceManage@0
    displayName: 'Swap Slots: $(appName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      WebAppName: $(appName)
      ResourceGroupName: '$(ResourceGroupName)'
      SourceSlot: staging

  - task: AzureAppServiceManage@0
    displayName: 'Stop staging Slot: $(appName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      Action: 'Stop Azure App Service'
      WebAppName: $(appName)
      ResourceGroupName: '$(ResourceGroupName)'
      SpecifySlotOrASE: true
      Slot: 'staging'
