jobs:
- job: 'CodeBuild'
  variables:
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-latest'
  workspace:
    clean: all
  steps:
    - task: UseDotNet@2
      displayName: "Use .NET Core SDK 2.1.x"
      inputs:
        packageType: 'sdk'
        version: '2.1.x'

    - task: NodeTool@0
      displayName: 'Node install'
      inputs:
        versionSpec: '16.x'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: src/Sfa.Tl.Find.Provider.Web
        verbose: false

    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetVersion)'
      inputs:
        packageType: sdk
        version: $(dotnetVersion)
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: gitversion/setup@3.1.1
      displayName: Install GitVersion
      inputs:
        versionSpec: '6.0.x'

    - task: gitversion/execute@3.1.1
      displayName: Update GitVersion
      inputs:
        updateAssemblyInfo: true

    - task: Gulp@0
      displayName: gulp
      inputs:
        gulpFile: src/Sfa.Tl.Find.Provider.Web/gulpfile.js
        targets: default

    - task: Cache@2
      displayName: Cache
      inputs:
        key: 'nuget | "$(Agent.OS)" | src\Sfa.Tl.Find.Provider.Web\package-lock.json'
        restoreKeys: |
          nuget | "$(Agent.OS)"
          nuget
        path: '$(NUGET_PACKAGES)'
        cacheHitVar: 'CACHE_RESTORED'      

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: 'src/**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: 'src/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*.UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'

    # - task: DotNetCoreCLI@2
    #   displayName: Integration Tests
    #   inputs:
    #     command: test
    #     projects: '**/*.Web.IntegrationTests.csproj'
    #     arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Website'
      inputs:
        command: publish
        publishWebProjects: true
        projects: 'src/Sfa.Tl.Find.Provider.Api/Sfa.Tl.Find.Provider.Api.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Publish Function App'
    #   inputs:
    #     command: publish
    #     publishWebProjects: false
    #     projects: 'src/Sfa.Tl.Find.Provider.Api.Functions/Sfa.Tl.Find.Provider.Api.Functions.csproj'
    #     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Publish Application Integration Tests'
    #   inputs:
    #     command: publish
    #     publishWebProjects: false
    #     projects: 'src/Sfa.Tl.Find.Provider.Api.Application.IntegrationTests/Sfa.Tl.Find.Provider.Api.Application.IntegrationTests.csproj'
    #     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Publish Web Integration Tests'
    #   inputs:
    #     command: publish
    #     publishWebProjects: false
    #     projects: 'src/Sfa.Tl.Find.Provider.Api.Web.IntegrationTests/Sfa.Tl.Find.Provider.Api.Web.IntegrationTests.csproj'
    #     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        contents: |
          azure/**
          config/**
        targetFolder: '$(build.artifactstagingdirectory)/publish'
        overWrite: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/publish'
          ArtifactName: 'appdrop'
          publishLocation: 'Container'