jobs:
  - job: PostDeployment
    pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'
    dependsOn: 
    - PublishSite_UI
    - PublishSite_API
    steps:
      - task: GitHubRelease@1
        displayName: 'GitHub release (create)'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main') , eq(variables['System.JobAttempt'], '1'))
        inputs:
          gitHubConnection: SkillsFundingAgency
          tagSource: userSpecifiedTag
          tag: '$(Build.BuildNumber)'