parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
  - name: tableName
    type: string
    default: 'configuration'
  - name: environmentName
    type: string
  - name: ConfigurationSecrets
    type: object
    default: {}
jobs:
- job: GenerateConfigs
  variables:
    ConfigStorageAccountName:     $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.ConfigStorageAccountName'] ]
    SqlConnectionString:          $[ dependencies.DeploySQLDatabase.outputs['SqlVariables.SqlConnectionString'] ]
    BlobStorageConnectionString : $[ dependencies.DeployfindproviderapiInfrastructure.outputs['armOutputs.armOutput.BlobStorageConnectionString'] ]
    RedisCacheName:               $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.RedisCacheName'] ]
    RedisCacheConnection:         $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.RedisConnectionString'] ]

  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  dependsOn: 
    - DeployfindproviderapiInfrastructure
    - DeploySQLDatabase
  steps:
    - checkout: self
    - checkout: devopsTools
    - task: AzurePowerShell@5
      inputs: 
        azurePowerShellVersion: 'LatestVersion'
        azureSubscription: ${{ parameters.serviceConnection }}
        scriptType: 'InlineScript'
        Inline: |
          $variableName = "RedisCacheConnectionString"
          Write-Host "Obtaining the connection string for $(RedisCacheName) and setting $variableName"
          $redisCache = Get-AzRedisCache -Name $(RedisCacheName)
          $primaryKey = (Get-AzRedisCacheKey -Name $(RedisCacheName)).PrimaryKey
          $connectionString = $redisCache.HostName + ":" + $redisCache.SslPort + ",password=" + $primaryKey + ",ssl=True,abortConnect=False"
          Write-Output "##vso[task.setvariable variable=$variableName;issecret=true]$connectionString"
          Write-Host "Variable $variableName set"

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'appdrop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzurePowerShell@5
      displayName: 'Generate API Configuration'
      inputs:
        azureSubscription: ${{ parameters.ServiceConnection }}
        ScriptType: 'FilePath'
        scriptPath: './operations-devops-tools/Powershell/GenerateConfig/New-ConfigurationTableEntry.ps1'
        scriptArguments:
          -SourcePath "$(System.ArtifactsDirectory)/appdrop/config"
          -TargetFilename "Sfa.Tl.Find.Provider.Api.schema.json"
          -StorageAccountName "$(ConfigStorageAccountName)"
          -StorageAccountResourceGroup "$(SharedResourceGroup)"
          -EnvironmentName ${{ parameters.environmentName }}
          -TableName "Configuration"
        azurePowerShellVersion: LatestVersion
        pwsh: true
        FailOnStandardError: true
      env: ${{ parameters.ConfigurationSecrets }}

    - task: AzurePowerShell@5
      displayName: 'Generate Web Configuration'
      inputs:
        azureSubscription: ${{ parameters.ServiceConnection }}
        ScriptType: 'FilePath'
        scriptPath: './operations-devops-tools/Powershell/GenerateConfig/New-ConfigurationTableEntry.ps1'
        scriptArguments:
          -SourcePath "$(System.ArtifactsDirectory)/appdrop/config"
          -TargetFilename "Sfa.Tl.Find.Provider.Web.schema.json"
          -StorageAccountName "$(ConfigStorageAccountName)"
          -StorageAccountResourceGroup "$(SharedResourceGroup)"
          -EnvironmentName ${{ parameters.environmentName }}
          -TableName "Configuration"
        azurePowerShellVersion: LatestVersion
        pwsh: true
        FailOnStandardError: true
      env: ${{ parameters.ConfigurationSecrets }}