CREATE NONCLUSTERED INDEX [IX_ProviderReference_UkPrn]
	ON [dbo].[ProviderReference](UkPrn) 
	INCLUDE([Urn]) 
	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]