CREATE NONCLUSTERED INDEX [IX_Town_TownName]
	ON [dbo].[Town]([TownName])
	INCLUDE([CountyName],[Latitude],[Longitude]) 
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
	ON [PRIMARY]
